### ISSUE TITLE
磨损有点忒大了

### ISSUE THREAD

**Issue by vvsuperman** [shuail0/aevoTrading#4]
貌似接近0.3%，撸秃了呀
刷5个eth磨损了30u，是哪里需要调整么？
市价单手续费就0.08%了，怎么做到10wu 磨损20的？

**Comment by shuail0** [comment]
你用的是哪个程序刷呢？我和身边的朋友用[aevo_market_price_trade.py](https://github.com/shuail0/aevoTrading/blob/main/aevo_market_price_trade.py) 单笔交易0.1E刷到10万U基本都是在20U以内的。

**Comment by ZZzzzioi** [comment]
实测下来50u总共刷了21w的交易量，可能boost的比较少，但是基本和老哥说的差不多
